export const PROPERTY = {
  name: 'KAP Home',
  tagline: 'Your Perfect Base in Chios, Greece',
  description:
    'A bright, modern apartment designed for independence, comfort and style. ' +
    'Warm décor with traditional Greek colours — nestled in the heart of Chios Town, ' +
    'steps from the sea, restaurants and everything the island has to offer.',
  location: {
    city: 'Chios Town',
    region: 'Chios Island',
    country: 'Greece',
    countryCode: 'GR',
    address: 'Chios Town Centre, Chios Island, Greece',
    coordinates: { lat: 38.3667, lng: 26.1333 },
    googleMapsEmbed:
      'https://maps.google.com/maps?q=38.3667,26.1333&z=15&output=embed',
  },
  stats: {
    size: '',
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 4,
    rating: 4.97,
    reviewCount: 28,
  },
  pricing: { currency: 'EUR', currencySymbol: '€' },
  distances: [
    { icon: '🏖️', label: 'Beach',         value: '< 1 km', detail: 'walking' },
    { icon: '✈️', label: 'Airport',        value: '11 min', detail: '3.8 km' },
    { icon: '🍽️', label: 'Restaurants',    value: '2 min',  detail: 'walking' },
    { icon: '🛒', label: 'Supermarket',    value: '5 min',  detail: 'walking' },
    { icon: '🏛️', label: 'Chios Old Town', value: '10 min', detail: 'walking' },
    { icon: '⛵', label: 'Ferry Port',     value: '8 min',  detail: 'walking' },
  ],
  amenities: [
    { icon: '📶', label: 'WiFi 200 Mbps',     desc: 'Fibre optic, blazing fast' },
    { icon: '🍳', label: 'Full Kitchen',       desc: 'Stove, oven, fridge, coffee maker' },
    { icon: '📺', label: 'Smart TV + Netflix', desc: 'Streaming included' },
    { icon: '🛁', label: 'Soaking Bathtub',    desc: 'Premium toiletries provided' },
    { icon: '🫧', label: 'Washing Machine',    desc: 'Detergent provided' },
    { icon: '🅿️', label: 'Free Parking',       desc: 'Private underground space' },
    { icon: '🌡️', label: 'Full Heating',       desc: 'Warm in every season' },
    { icon: '🌿', label: 'Sunny Balcony',       desc: 'City views, seating area' },
  ],
  images: {
    hero:          '/images/hero-main.jpg',
    bedroom:       '/images/bedroom.jpg',
    bedroomDetail: '/images/bedroom-detail.jpg',
    livingRoom:    '/images/living-room.jpg',
    exterior:      '/images/exterior.jpg',
    bathroom:      '/images/bathroom.jpg',
    og:            '/images/og.jpg',
  },
  gallery: [
    { src: '/images/hero-main.jpg',      alt: 'KAP Home open-plan living and dining area, Chios' },
    { src: '/images/bedroom.jpg',        alt: 'KAP Home double bedroom with wooden wardrobe, Chios' },
    { src: '/images/bathroom.jpg',       alt: 'KAP Home bathroom with soaking bathtub, Chios' },
    { src: '/images/living-room.jpg',    alt: 'KAP Home living room with Smart TV and Netflix, Chios' },
    { src: '/images/exterior.jpg',       alt: 'KAP Home balcony garden with roses, Chios' },
    { src: '/images/bedroom-detail.jpg', alt: 'KAP Home bedroom amenities and toiletries, Chios' },
  ],
  reviews: [
    {
      id: 1,
      author:   'Ender',
      country:  'Turkey 🇹🇷',
      source:   'Booking.com',
      score:    '10 / 10',
      date:     'August 2025',
      text:     'A quiet, cool apartment very close to the city centre. Everything was spotlessly clean — the balcony, kitchen and bathroom were all immaculate. Perfect stay.',
      stayType: 'Family',
    },
    {
      id: 2,
      author:   'Kostara',
      country:  'Greece 🇬🇷',
      source:   'Booking.com',
      score:    '10 / 10',
      date:     'August 2025',
      text:     'Excellent in every way. Great location, comfortable rooms, and everything you need is there. Would book again without hesitation.',
      stayType: 'Solo traveller',
    },
    {
      id: 3,
      author:   'Ayşen',
      country:  'Turkey 🇹🇷',
      source:   'Airbnb',
      score:    '★★★★★',
      date:     'August 2025',
      text:     'Everything was beautiful and spotlessly clean. Excellent facilities with a fully-stocked kitchen. Great central location — walking distance from everywhere. The hospitality made us feel right at home as a family.',
      stayType: 'Family',
    },
  ],
  host: {
    name:      'Pavlos',
    phone:     '+306948078882',
    whatsapp:  'https://wa.me/306948078882',
  },
  seo: {
    title:       'KAP Home Chios | Book Direct & Save — Modern Apartment in Chios, Greece',
    description: 'Book KAP Home directly in Chios, Greece. Bright apartment for up to 4 guests in the city centre — beach under 1 km, free parking, 200 Mbps WiFi. No Airbnb fees. Best price guaranteed at €90/night.',
    keywords: [
      'chios accommodation','chios apartment rental','rent apartment chios',
      'chios greece holiday','vacation rental chios','kap home chios',
      'chios short term rental','book direct chios','airbnb alternative chios',
      'chios island stay','chios greece apartment','where to stay chios greece',
    ],
  },
} as const

export type Property = typeof PROPERTY
